numbers = set()

n = input('Enter the number:')
numbers.add(int(n))
n = input('Enter the number:')
numbers.add(int(n))
n = input('Enter the number:')
numbers.add(int(n))
n = input('Enter the number:')
numbers.add(int(n))
n = input('Enter the number:')
numbers.add(int(n))
n = input('Enter the number:')
numbers.add(int(n))
n = input('Enter the number:')
numbers.add(n)
n = input('Enter the number:')
numbers.add(int(n))

print(numbers)